name: test issue
description: test issue form
title: Enviornment

body:

- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
      
- type: input
  id: Start_Date
  attributes:
    label: Change start date
    description: "start date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
- type: input
  id: End_Date
  attributes:
    label: Change END date
    description: "End date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
    
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
