name: test issue
description: test issue form
title: Enviornment

body:

- type: markdown
  attributes:
    value: |
      Change effecting
      
- type: input
  id: Start_Date
  attributes:
    label: Change start date
    description: "Change start date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
    
- type: input
  id: End_Date
  attributes:
    label: Change end date
    description: "Change end date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
    
- type: dropdown
  id: ENV
  attributes:
    label: Enviornment
    options:
      - sbox
      - aat
      - preview
      - test
      - staging
      - perftest
      - demo
      - ithc
      - dev
  validations:
    required: true

- type: dropdown
  id: download
  attributes:
    label: Business unit
    options:
      - cft
      - sds
  validations:
    required: true
