name: learn-github-actions
run-name: ${{ github.actor}} is running
on:
  push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    name: 'j1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
        name: 'j1setp4'
      - run: bats -v