name: github actions 1
run-name: ${{ github.actor }} is
on: [push]
jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
      - name: "step1"
        run: echo "step1"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: {{ github.reg}}