name: github_actions_1
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main]
    paths:  [README*]
    
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: echo $GITHUB_WORKFLOW_SHA
      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${sha}-${ts}
          
      - name: out
        run: |
           echo ${{ steps.prep.outputs.BUILD_ID }}
        
        
        
        
        # - uses: octokit/request-action@v2.x
#         id: get_latest_release
#         with:
#           route: GET "/repos/hmcts/sds-flux-config/commits/${{ env.GB_SHA }}/pulls"
#           owner: octokit
#           repo: request-action
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GB_SHA: echo $GITHUB_SHA
      
          
#       - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
