name: push shutter pages to webapp
on:
  workflow_call:
    secrets:
      WEBAPP_TOKEN:
        required: true
        description: Static webapp deployment token
    inputs:
      shutter_page_folder:
        required: true
        type: string 

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: My first step
        uses: actions/hello_world@main
        with:
          first_name: ${{ secrets.WEBAPP_TOKEN }}
          middle_name: The
          last_name: Octocat
          
