name: Parse github form
run-name: ${{ github.actor }}
on:
  issues:
    types:
      - opened
      - labeled
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Display the path
        run: echo ${{ secrets.GITHUB_TOKEN }}
        shell: bash
