name: Parse github form
run-name: ${{ github.actor }}
on:
  issues:
    types:
      - opened
      - labeled
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Display the path
        run: echo ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}

      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'

          # Print the value of the "Name" field
          echo '${{ fromJson(steps.parse.outputs.payload)["Name"] }}'
