name: Parse github form
run-name: ${{ github.actor }}
on:
  issues:
    types:
      - opened
      - labeled
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Display the path
        run: echo ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
      
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue

      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'
          echo "NEW_DATA=${{ steps.parse.outputs.payload }}" >> $GITHUB_ENV
          

        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: |
          python file_handling.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "crongenerated"
          git push
        
