#name: Parse github form
run-name: Housekeeping issues json file
on:
  schedule:
    - cron:  '00 18 * * *'
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
     
       
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: |
          python file_handling.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "housekeeping"
          git push
        