name: matrix
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  validate-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: tst
            client_id: TST_TF_ARM_CLIENT_ID
            client_secret: TST_TF_ARM_CLIENT_SECRET
            subscription_id: TST_TF_ARM_SUBSCRIPTION_ID
          - environment: acc
            client_id: ACC_TF_ARM_CLIENT_ID
            client_secret: ACC_TF_ARM_CLIENT_SECRET
            subscription_id: ACC_TF_ARM_SUBSCRIPTION_ID
          - environment: prd
            client_id: PRD_TF_ARM_CLIENT_ID
            client_secret: PRD_TF_ARM_CLIENT_SECRET
            subscription_id: PRD_TF_ARM_SUBSCRIPTION_ID
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets[matrix.client_id] }}
      ARM_CLIENT_SECRET: ${{ secrets[matrix.client_secret] }}
      ARM_SUBSCRIPTION_ID: ${{ secrets[matrix.subscription_id] }}
    steps:
      - name: bashc
        run: |
          echo ${{ env.ARM_CLIENT_ID }}
