name: matrix
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: bashs
        run: |
          echo ${{ matrix.version }}
          echo ${{ matrix.os }}
        shell: bash
