name: Netbox
run-name: Netbox
on:
  push:
    branches:
      - "main"
    paths:
      - /apps/netbox/ptl/netbox.yaml
workflow_dispatch:

jobs:
  netbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3