#name: Parse github form
run-name: ${{ github.actor }} - issue:${{ github.event.issue.number }}
on:
  issues:
    types:
      - opened
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Parse issue
        id: parse_issue
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
      
      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse_issue.outputs.payload }}'
          echo NEW_DATA='${{ steps.parse_issue.outputs.payload }}' >> $GITHUB_ENV
          
       
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: |
          python file_handling.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b PR-${{ github.event.issue.number }}
          git add .
          git commit -m "parseissues"
          git push --set-upstream origin PR-${{ github.event.issue.number }}
          gh pr create -f -t PR-${{ github.event.issue.number }} -t ${{ github.run_id }}
          gh pr edit PR-${{ github.event.issue.number }} -t ${{ github.run_id }}  --add-label automerge --repo hmcts/${{github.repository}} 
        env:
          GH_TOKEN: ${{ github.token }}
      - run: | # approve the pull request
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/$GITHUB_SHA/reviews \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}'  
        env:
          GH_TOKEN: ${{ github.token }}
          
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue
