name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main]
    paths:  [README*]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-reqs
        run: |
          sudo apt update
          sudo apt-get install -y jq
          sudo apt-get install -y gh
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
      - run: env
      - name: testing
        if: contains(env.GITHUB_SHA_SHORT, 'a')
        run: echo "TS-----"
      - name: testing
        if: "!contains(${{ env.GITHUB_SHA_SHORT }}, 'aaac')"
        run: echo "TS---ssss--"
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: all
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo ${{ steps.findPr.outputs.pr }}
      - run: echo $(gh pr view ${{ steps.findPr.outputs.pr }} --json mergeCommit -q .mergeCommit.oid )
        env:
          GH_TOKEN: ${{ github.token }}
  
